export const LoremIpsum = `
"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."
freestar
freestar
<br /><br />
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam massa tellus, porta in libero id, imperdiet tincidunt dolor. Donec volutpat sollicitudin metus, quis tempus mi congue quis. Nulla id interdum dolor, at euismod magna. Quisque blandit condimentum mollis. Sed varius dictum lacus, non aliquam tortor blandit vitae. Sed dui augue, consequat hendrerit laoreet ac, sollicitudin vel nisi. Duis et felis a massa pharetra facilisis tempus at ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis ac ornare justo. Vivamus eu elit fermentum, condimentum nibh at, euismod magna. Donec maximus nec nisl ullamcorper pellentesque. Quisque tempor nibh turpis, id congue enim egestas sed. Nam accumsan semper metus at condimentum.
<br /><br />
Nunc ut mauris at erat condimentum tempor. Etiam euismod sit amet odio sed bibendum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean ut malesuada nibh. Maecenas varius ante in turpis imperdiet rhoncus. Etiam nulla lorem, dapibus a nisi vitae, tempor fringilla turpis. Nulla facilisi. Sed sit amet turpis eu dolor tempor accumsan non gravida nisi. Praesent vel ipsum augue. Nunc sollicitudin, ligula a aliquam iaculis, ante nunc efficitur erat, in interdum nibh enim quis odio. Phasellus venenatis pharetra pretium.
<br /><br />
Nulla tempor pretium lacus non pulvinar. Morbi nec sodales ipsum, a pulvinar leo. Vestibulum at turpis urna. Cras nec lobortis sapien, eget euismod lorem. Curabitur tincidunt tempor gravida. Etiam nisl dui, accumsan sed accumsan vel, lobortis venenatis leo. Pellentesque ac lorem sollicitudin, aliquet odio eget, auctor magna. Aliquam malesuada ex urna, vitae consequat nibh congue non. Proin malesuada, magna a ornare aliquet, est risus pulvinar nibh, sit amet sollicitudin tortor leo vitae arcu.
<br /><br />
Sed sem libero, pretium eget consequat bibendum, posuere vel dolor. Donec vitae malesuada tellus, vulputate finibus arcu. Mauris iaculis mi interdum urna tincidunt, eu vulputate lectus aliquam. Pellentesque maximus tempor urna et imperdiet. Cras vitae sagittis dui. Etiam at libero nunc. Sed arcu metus, mollis sollicitudin massa eu, vulputate congue velit. Fusce dapibus posuere erat. Praesent et arcu in ligula vehicula imperdiet. Proin mauris dolor, tincidunt quis volutpat vel, iaculis id lorem.
<br /><br />
Etiam ut tincidunt nunc. Aliquam euismod pretium dignissim. Quisque et fermentum eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor ac magna pellentesque tempus. Quisque et enim vitae nulla maximus convallis ac et tortor. Praesent lorem velit, imperdiet vel imperdiet ut, porttitor eu lectus.
<br /><br />
In ut massa rutrum, fermentum arcu a, blandit erat. Maecenas nec sem ut libero iaculis viverra. Nunc malesuada tellus nec tellus tincidunt, ut malesuada dolor sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse hendrerit nisi tempor mattis tempor. In ut augue sed nisi varius varius eu ut nibh. In gravida urna ac sem congue, ac sodales quam mollis. Aenean posuere nisl id diam congue, dignissim tempus justo tincidunt. Aliquam nec mi nisl.
<br /><br />
Donec finibus neque a enim lacinia tempor et eget lorem. In luctus in lacus sit amet vulputate. Quisque quis tincidunt eros. Integer finibus aliquet metus, eu vehicula dolor dictum sodales. Pellentesque sit amet libero ante. Suspendisse ut sem efficitur, scelerisque magna in, faucibus nisl. Integer dignissim placerat feugiat.
<br /><br />
Proin odio diam, faucibus vel nulla eget, mattis interdum leo. Donec ut dapibus nulla. Pellentesque a libero ac est congue consectetur. Mauris ut purus ac leo tristique volutpat quis sit amet nisi. Integer urna mi, rutrum in libero non, eleifend semper orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam nec sollicitudin enim, sed varius elit. Pellentesque placerat quis risus sit amet ullamcorper. Aenean non ante ultricies, gravida tellus a, gravida magna. Vivamus non massa a mauris pharetra venenatis eu at ex. Vestibulum quis libero eros. Ut quis augue imperdiet, volutpat risus nec, imperdiet elit. Integer a dolor ac dolor congue pulvinar.
<br /><br />
Proin faucibus lobortis fermentum. Aliquam porttitor ac mi non consequat. Curabitur pretium, orci nec eleifend pellentesque, neque ipsum feugiat nibh, eu bibendum libero libero ut massa. Nulla facilisi. Nulla efficitur vestibulum nisi, eget aliquet velit commodo sed. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi at tincidunt risus. Ut accumsan feugiat nulla at eleifend. Suspendisse potenti. Vivamus ultrices egestas quam, sed convallis risus. Ut hendrerit, massa eu cursus consequat, urna ex varius arcu, vitae aliquet dui nibh vel ipsum. Aliquam erat volutpat. Cras interdum vulputate neque, vitae facilisis arcu vestibulum a. Aenean ornare nulla commodo turpis aliquet, ut volutpat lorem interdum. Vestibulum congue egestas pretium.
<br /><br />
Nulla a tellus ante. Integer in urna convallis, finibus dui ut, finibus ligula. Mauris rhoncus interdum gravida. Morbi vitae rutrum enim. Vivamus convallis rutrum faucibus. Aliquam scelerisque, velit vel pretium cursus, dolor elit cursus magna, eu maximus eros est efficitur neque. Nam magna eros, iaculis sit amet vulputate vitae, molestie a dui. Mauris accumsan, ex sit amet tristique convallis, metus justo fringilla risus, dignissim eleifend enim orci id arcu. Maecenas vitae pretium purus. Praesent quam nisl, faucibus nec congue vitae, placerat sit amet odio. Nulla quis est nibh. Ut ultricies, odio eu aliquet molestie, eros eros congue neque, sit amet hendrerit erat est non dui.
`;